version: "3.0"

services:
  db:
    image: postgres:alpine
    container_name: keeppri_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:alpine
    container_name: keeppri_redis
    command:
      - redis-server
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=YES
    volumes:
      - redis-data:/data
    restart: always

  migrate:
    image: migrate/migrate
    container_name: keeppri_migrate
    restart: on-failure
    command:
      - -path
      - /migrations
      - -database
      - postgres://postgres:postgres@db:5432/postgres?sslmode=disable
      - up
    volumes:
      - ./migrations:/migrations

  auth:
    container_name: keeppri_service_auth
    build: .
    ports:
      - "50051:50051"
    restart: unless-stopped
    environment:
      - CONFIG_PATH=./config/dev.yaml
    depends_on:
      - db
      - redis
      - migrate

  dozzle:
    image: amir20/dozzle:latest
    container_name: keeppri_dozzle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8888:8080"
    env_file:
      - .env

volumes:
  redis-data:
  postgres-data: