env: "dev"
version: 0.0.0

grpc:
  port: 50051
  timeout: 10m

postgres:
  host: db
  port: 5432
  user: postgres
  password: postgres
  db: postgres

redis:
  host: redis
  port: 6379
  db: 0
  password: redis

token:
  session_token_size: 32