env: "local"
version: 0.0.0

grpc:
  port: 50051
  timeout: 10m

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db: auth_db

redis:
  host: localhost
  port: 6379
  db: 0
  password: redis